import type { Metadata } from 'next';
import { body } from '@/libs/fonts';
import './globals.css';
import { NavBar } from '@/components/NavBar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${body.className} antialiased text-slate-200 bg-slate-950 overflow-x-hidden`}
      >
        <NavBar />
        <main className='flex flex-col gap-y-10'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
