import type { Metadata } from 'next';
import { body } from '@/libs/fonts';
import './globals.css';
import { NavBar } from '@/components/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${body.className}  antialiased text-slate-200 bg-slate-950`}
      >
        <NavBar />
        <main className='flex flex-col container m-auto'>{children}</main>
      </body>
    </html>
  );
}
